### PR TITLE
Use EntityName as opposed to entities class name in queries

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
Fix for https://github.com/Blazebit/blaze-persistence/issues/466

### CODE REVIEW

**Comment by beikov** [comment]
Would you mind changing the commit message to "#466 - Use entity name as opposed to entity class name in queries to fix #466" and rebase it against my issues/414 branch?

**Comment by jwgmeligmeyling** [comment]
Sure, I’ll reapply it in a bit. As far as I remember I already based it on 414 though, or have there been some squashes?


Jan-Willem


Op 6 nov. 2017 om 18:34 heeft Christian Beikov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Would you mind changing the commit message to "#466<https://github.com/Blazebit/blaze-persistence/issues/466> - Use entity name as opposed to entity class name in queries to fix #466<https://github.com/Blazebit/blaze-persistence/issues/466>" and rebase it against my issues/414 branch?

**Comment by beikov** [comment]
I rebased my 414 branch as I am about to apply it to master.

**Comment by beikov** [comment]
Or even, better. Do the rebase against the master as I just merged 414 and provide a PR against that please.

**Pull request closed without merging**
